### PR TITLE
Bugfix

### PR DESCRIPTION
**Pull request by explodingcamera**
Leveldb needs the DB folder

### CODE REVIEW

**Comment by DerpgonCz** [comment]
It should be checked whether any of the features that requires working email are set before attempting to initializing the mailer file and authorize with the options against the email server, not just setting options.auth to not be null

**Comment by explodingcamera** [comment]
ok, removed the config commit

**Comment by explodingcamera** [comment]
Added fix, lounge iframe pointed to the wrong url

**Comment by DerpgonCz** [comment]
Fixed in commit https://github.com/musiqpad/mqp-server/commit/456a8a57e23ccfab1b92c0cbe7e525a89275c613

**Pull request closed without merging**
